name: Package and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create keys.py and inject secret
      env:
        TWTR_SECRET: ${{ secrets.T_ENV }}
      run: |
        echo "TWTR_SECRET = '$TWTR_SECRET'" > ./keys.py

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package project
      run: |
        mkdir package
        cp -r ./* package/
        cd package
        pip install -r ../requirements.txt -t .
        zip -r ../lambda_package.zip .

  deploy:
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-awscredentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name GE-Bot --zip-file fileb://lambda_package.zip
