name: Package and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package project
      run: |
        mkdir package
        rsync -Rr ./* package/
        cd package
        pip install -r ../requirements.txt -t .
        zip -r ../lambda_package.zip .
   
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda_package
        path: lambda_package.zip

  deploy:
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: lambda_package

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Configure AWS Credentials For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name GE-Bot --zip-file fileb://lambda_package.zip
        
    - name: Update Lambda environment variable with secret
      run: |
        aws lambda update-function-configuration --function-name GE-Bot --environment "Variables={TWTR_SECRET=${{ secrets.T_ENV }}}"
